name: Continuous Integration

on:
  push:
    branches:
    - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: creyD/autoflake_action@master
      with:
        options: -r --in-place --remove-all-unused-imports
